package com.lemoulinstudio.gfa.nb.screen;

import com.lemoulinstudio.gfa.core.gfx.GfaScreen;
import com.lemoulinstudio.gfa.nb.filetype.rom.RomDataObject;

/**
 * Top component which displays the screen of the gfa device.
 */
public final class DefaultScreenTopComponent extends ScreenTopComponent {

  private GfaScreen gfaScreen;

  public DefaultScreenTopComponent(RomDataObject dataObject) {
    super(dataObject);

    gfaScreen = new GfaScreen(dataObject.getGfaDevice().getLcd());

    initComponents();
    
    add(gfaScreen);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.CardLayout());
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

}
