package com.lemoulinstudio.gfa.nb.screen;

import com.lemoulinstudio.gfa.core.gfx.GfaScreen;
import com.lemoulinstudio.gfa.nb.filetype.rom.RomDataObject;
import com.lemoulinstudio.gfa.nb.util.CentralLookup;
import com.lemoulinstudio.gfa.nb.GfaContext;

/**
 * Top component which displays something.
 */
public final class DefaultScreenTopComponent extends ScreenTopComponent {

  private GfaScreen gfaScreen;

  public DefaultScreenTopComponent(RomDataObject dataObject) {
    super(dataObject);
    gfaScreen = new GfaScreen();

    initComponents();
    
    add(gfaScreen);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setLayout(new java.awt.CardLayout());
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables

  @Override
  public void componentOpened() {
  }

  @Override
  protected void componentActivated() {
    CentralLookup gfaLookup = GfaContext.lookup;

    synchronized (gfaLookup) {
      for (Object o : gfaLookup.lookupResult(RomDataObject.class).allInstances())
        gfaLookup.remove(o);

      gfaLookup.add(dataObject);
    }
  }

  @Override
  protected void componentDeactivated() {
  }

  @Override
  public void componentClosed() {
    GfaContext.lookup.remove(dataObject);
    
    // Todo: ask the data source to release the reference.
  }

}
